build:
  modules:
  - ninja
  dependencies:
  - ecmwf/ecbuild@develop
  - MathisRosenhauer/libaec@refs/tags/v1.1.3
  - ecmwf/eccodes@develop
  - ecmwf/eckit@develop
  - ecmwf/odc@develop
  - ecmwf/metkit@develop
  - ecmwf/fdb@develop
  python_dependencies:
  - ecmwf/eccodes-python@develop
  - ecmwf/cfgrib@master
  - ecmwf/pdbufr@master
  - ecmwf/pyodc@develop
  - ecmwf/pyfdb@develop
  env:
  - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
  - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
  parallel: 64
  queue: ng
  gpus: 1
  toml_opt_dep_sections: all,test,ci
  pytest_cmd: |
    python -m pytest -vv -m 'not notebook and not no_cache_init' --cov=. --cov-report=xml
    #python -m pytest -v -m 'notebook'
    #python -m pytest --forked -vv -m 'no_cache_init'
    #python -m coverage report
