name: earthkit-data
channels:
- conda-forge
- nodefaults
dependencies:
- eccodes=>2.19.0
- python-eccodes
- pip
- numpy
- pandas
- xarray>=0.19.0
- dask
- netcdf4
- cfgrib>=0.9.10.1
- pdbufr
- pyodc
- filelock
- pyyaml
- entrypoints
- jupyterlab
- pip:
  - git+https://github.com/ecmwf/multiurl
- tqdm
- make
- mypy
- myst-parser
- pre-commit
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinx-autoapi
- sphinx_rtd_theme
- sphinxcontrib-apidoc
- nbformat
- nbconvert
- nbsphinx
- ipykernel
