channels:
- conda-forge
- nodefaults
dependencies:
- make
- mypy
- myst-parser
- pre-commit
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinxcontrib-apidoc
- cf-units
- xarray
- numpy
- pandas
- geopandas
- netcdf4
- h5netcdf
- dask
