name: earthkit-data
channels:
- conda-forge
- nodefaults
dependencies:
- eccodes=>2.35.0
- python-eccodes>=1.7.0
- pip
- numpy
- pandas
- xarray>=0.19.0
- dask
- netcdf4
- cfgrib>=0.9.10.1
- pdbufr>=0.11.0
- pyodc
- filelock
- pyyaml
- entrypoints
- jupyterlab
- ecmwf-api-client>=1.6.1
- cdsapi>=0.7.2
- hda>=2.22
- pip:
  - multiurl>=0.3.3
  - pyfdb>=0.1.0
  - ecmwf-opendata>=0.1.2
  - polytope-client>=0.7.4
  - earthkit-meteo>=0.0.1
  - covjsonkit>=0.2.0
  - earthkit-geo>=0.2.0
  - earthkit-utils>=0.1.1
- tqdm>=4.63.0
- lru-dict
- markdown
- aws-requests-auth
- botocore
- make
- mypy
- myst-parser
- pre-commit
- pydata-sphinx-theme
- pyfakefs
- pytest
- pytest-cov
- pytest-forked
- pytest-timeout
- sphinx>=7.2.6
- pip:
  - sphinx-autoapi>=3.0.0
- sphinx_rtd_theme
- sphinxcontrib-apidoc
- sphinx-issues
- sphinx-tabs
- sphinx-copybutton
- nbformat
- nbconvert
- nbsphinx
- ipykernel
- geopandas
- deprecation
